name: mldd24
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cpuonly=2.0
  - biopython=1.83
  - black=24.2.0
  - bokeh=3.3.4
  - chembl_webresource_client=0.10.9
  - isort=5.13.2
  - jupyter=1.0.0
  - matplotlib=3.5.3
  - notebook=7.1.1
  - numpy=1.26.4
  - openbabel=3.1.1
  - pandas=2.2.1
  - pip=24.0
  - prolif=2.0.1
  - py3dmol=2.0.4
  - pyg=2.5.0
  - pymol-open-source=2.5.0
  - pypdb=2.3
  - pytdc=0.3.8
  - pytest=8.0.2
  - python=3.10.13,<3.11
  - pytorch=2.2.1
  - pytorch-lightning=2.1.3
  - pyyaml=6.0.1
  - qvina=2.1.0
  - rdkit=2022.03.5
  - scikit-learn=1.4.1.post1
  - scipy=1.12.0
  - seaborn=0.13.2
  - smina=2020.12.10
  - streamlit
  - tqdm=4.66.2
  - yaml=0.2.5
